local Chunk = Class {
    init = function(self)
        self.image = nil
        self.data = { -- all voxels generated by noises
            [1] = {
                [1] = { -- x,y coords
                    resourceId = 1,
                    quantity = 0.5
                }
            }
        }
        self.changes = {} -- only changed voxels
    end
}

function Chunk:setVoxel(position, voxelData)
    -- for initialisation
end

function Chunk:changeVoxel(position, voxelData)
    -- add changes, overlay them over base data
end

function Chunk:serialize()
    -- return data to save
end

function Chunk:getVoxel(position)
    -- return hardness of that voxel and resources
end

function Chunk:generateImage()
    -- generate ImageData
    -- save to Image
end

function Chunk:update(dt)
    -- load/unload chunks here?
    -- or send/receive chunks to thread?
end

function Chunk:draw()
    -- draw image at 0,0
    -- draw changes over image
end

return Chunk
